"""Whole-repository module map: files, their imports, and each file's last commit. Lane 2.

Generated by code from the source tree and git history, never by a model. An import that
cannot be resolved is recorded as an unknown rather than dropped, because a missing edge must
never be mistaken for "this file affects nothing".

File level only: which *function* calls which belongs to the per-PR evidence map, not here.
The map answers "where does this change sit in the whole project", which the evidence map
does not.

Python is analysed with the stdlib `ast` module, so no optional dependency is needed. Other
languages are listed as modules without edges and a limit line that says so, until the
language adapters land; the map never claims an edge it did not resolve.
"""

from __future__ import annotations

import ast
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

SCHEMA_VERSION = "1"

# "Merge pull request #22 from …" (merge commit) or "… (#22)" (squash commit).
_PR_NUMBER = re.compile(r"Merge pull request #(\d+)|\(#(\d+)\)\s*$")

# Directories that never hold first-party source worth mapping.
_SKIP_DIRS = {
    ".git", ".venv", "venv", "env", "node_modules", "build", "dist", "__pycache__",
    ".pytest_cache", ".mypy_cache", ".tox", ".eggs", "site-packages", ".bobreviewer",
}

# Extension to language name. Python is the only one with an analyser today.
_LANGUAGES: dict[str, str] = {
    ".py": "python",
    ".ts": "typescript", ".tsx": "typescript",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".java": "java", ".cs": "csharp", ".go": "go", ".rs": "rust",
}

# The tier an adapter would advertise. Only Python has execution evidence in this tool.
_TIERS = {"python": "full"}
_TIER_FALLBACK = "static_same_file"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _tier_for(language: str) -> str:
    return _TIERS.get(language, _TIER_FALLBACK)


def _iter_source_files(root: Path) -> Iterable[Path]:
    """Every first-party source file under *root*, in a stable order."""
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        parts = path.relative_to(root).parts
        if any(part in _SKIP_DIRS for part in parts):
            continue
        if path.suffix.lower() not in _LANGUAGES:
            continue
        yield path


def last_commits(repo_root: Path, sha: str) -> dict[str, dict]:
    """The newest commit touching each path, from one `git log` pass.

    First-parent history with merges diffed against their first parent attributes a file to
    the "Merge pull request #N" (or squash "(#N)") commit that brought it in, which is how the
    PR number is recovered. Doing this in a single pass keeps the map cheap on a large repo.
    """
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_root), "log", sha, "--first-parent",
             "--diff-merges=first-parent", "--format=%x1e%H%x09%cs%x09%s", "--name-only"],
            capture_output=True, text=True, encoding="utf-8", timeout=60,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return {}
    if result.returncode != 0:
        return {}

    commits: dict[str, dict] = {}
    for chunk in result.stdout.split("\x1e")[1:]:
        lines = chunk.strip("\n").split("\n")
        if not lines or not lines[0].strip():
            continue
        header, *paths = lines
        fields = header.split("\t", 2)
        if len(fields) != 3:
            continue
        commit_sha, date, subject = fields
        match = _PR_NUMBER.search(subject)
        record = {
            "sha": commit_sha[:7],
            "date": date,
            "subject": subject,
            "pr": int(match.group(1) or match.group(2)) if match else None,
        }
        for path in paths:
            path = path.strip()
            if path and path not in commits:
                commits[path] = record
    return commits


def _module_path_for(relative: str) -> str:
    """The dotted module name a repo-relative path would import as."""
    stem = relative[:-3] if relative.endswith(".py") else relative
    parts = stem.split("/")
    if parts and parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(part for part in parts if part)


def _resolve_relative(module: str, level: int, current: str) -> str | None:
    """Resolve a relative import against the importing file's own package."""
    if level <= 0:
        return module
    parts = current.split(".") if current else []
    if parts and parts[-1] == "__init__":
        parts = parts[:-1]
    # `level` counts dots: one dot is the current package, two the parent, and so on.
    base = parts[: len(parts) - (level - 1)] if level > 1 else parts
    if level > 1 and not base:
        return None
    return ".".join([*base, module]) if module else ".".join(base) or None


def python_imports(path: Path, relative: str) -> tuple[list[dict], list[dict]]:
    """Import edges out of one Python file, plus the ones that could not be resolved.

    Returns ``(edges, unknowns)`` where each edge is ``{"target_module", "line"}`` and each
    unknown carries the source line and a reason. A file that will not parse yields one
    unknown, not an exception: the map still describes the rest of the repository.
    """
    try:
        source = path.read_text(encoding="utf-8", errors="replace")
        tree = ast.parse(source, filename=str(path))
    except (SyntaxError, ValueError, OSError) as exc:
        return [], [{"line": 1, "expression": path.name,
                     "reason": f"could not parse: {type(exc).__name__}"}]

    current_module = _module_path_for(relative)
    edges: list[dict] = []
    unknowns: list[dict] = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name:
                    edges.append({"target_module": alias.name, "line": node.lineno})
        elif isinstance(node, ast.ImportFrom):
            resolved = _resolve_relative(node.module or "", node.level or 0, current_module)
            if resolved:
                edges.append({"target_module": resolved, "line": node.lineno})
                for alias in node.names:
                    if alias.name and alias.name != "*":
                        edges.append({"target_module": f"{resolved}.{alias.name}", "line": node.lineno})
            else:
                unknowns.append({
                    "line": node.lineno,
                    "expression": f"{'.' * (node.level or 0)}{node.module or ''}",
                    "reason": "relative import escapes the repository root",
                })
        elif isinstance(node, ast.Call):
            # `importlib.import_module("x")` and `__import__("x")`: a real dependency the
            # static graph cannot see, so it is reported instead of ignored.
            func = node.func
            name = getattr(func, "attr", None) or getattr(func, "id", None)
            if name in {"import_module", "__import__"} and node.args:
                first = node.args[0]
                if isinstance(first, ast.Constant) and isinstance(first.value, str):
                    edges.append({"target_module": first.value, "line": node.lineno})
                else:
                    unknowns.append({
                        "line": node.lineno,
                        "expression": f"{name}(...)",
                        "reason": "dynamic import with a non-constant argument",
                    })

    return edges, unknowns


def build(checkout: Path, repo_root: Path, repo: str, sha: str) -> dict:
    """Build the repository map for one revision.

    *checkout* is the revision's worktree (where sources are read from); *repo_root* is the
    long-lived repository used for git history. Nothing here is model-generated.
    """
    checkout = Path(checkout)
    repo_root = Path(repo_root)
    commits = last_commits(repo_root, sha)

    modules: list[dict] = []
    raw_edges: list[dict] = []
    unknowns: list[dict] = []

    # Index every module so an import can be joined to a real file instead of matching by
    # guesswork. Both the dotted module path and its package (`pkg.mod` -> `pkg`) are keys.
    index: dict[str, str] = {}
    files: list[tuple[Path, str, str]] = []
    for path in _iter_source_files(checkout):
        relative = path.relative_to(checkout).as_posix()
        language = _LANGUAGES[path.suffix.lower()]
        files.append((path, relative, language))
        modules.append({
            "path": relative,
            "language": language,
            "tier": _tier_for(language),
            "last_commit": commits.get(relative),
        })
        if language == "python":
            dotted = _module_path_for(relative)
            if dotted:
                index.setdefault(dotted, relative)
                parts = dotted.split(".")
                for depth in range(1, len(parts)):
                    index.setdefault(".".join(parts[:depth]), relative)

    for path, relative, language in files:
        if language != "python":
            continue  # no analyser for this language yet; listed as a module, no edges
        edges, unresolved = python_imports(path, relative)
        for edge in edges:
            target = index.get(edge["target_module"])
            if target is None:
                # Not a first-party module (a library, or a package we do not index). Not an
                # unknown: a third-party import is resolved information, it just has no node.
                continue
            if target == relative:
                continue  # a self-import is not an edge in the graph
            raw_edges.append({"from": relative, "to": target, "kind": "import", "line": edge["line"]})
        for item in unresolved:
            unknowns.append({"path": relative, "line": item["line"],
                             "expression": item["expression"], "reason": item["reason"]})

    # One edge per file pair, keeping the earliest line so the map stays readable.
    best: dict[tuple[str, str], int] = {}
    for edge in raw_edges:
        key = (edge["from"], edge["to"])
        if key not in best or edge["line"] < best[key]:
            best[key] = edge["line"]

    other_languages = sorted({m["language"] for m in modules if m["language"] != "python"})
    limits = [
        "File-level imports only; which function calls which is in the per-PR evidence map.",
        "Imports of packages outside this repository are not drawn: they have no module here.",
        "Imports the analyser cannot resolve (dynamic, or escaping the repository root) are "
        "listed as unknowns, never dropped.",
        f"Last commit per module is taken from git history at {sha[:7]}.",
    ]
    if other_languages:
        limits.append(
            "Static structure only for "
            + ", ".join(other_languages)
            + ": these files are listed without import edges, and no tests or probes are run "
            "for them."
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "repo": repo,
        "sha": sha,
        "generated_at": _now_iso(),
        "modules": sorted(modules, key=lambda module: module["path"]),
        "edges": [{"from": src, "to": dst, "kind": "import", "line": line}
                  for (src, dst), line in sorted(best.items())],
        "unknowns": sorted(unknowns, key=lambda item: (item["path"], item["line"])),
        "limits": limits,
    }


def write_map(payload: dict, destination: Path) -> Path:
    """Write the map as JSON next to a run, or wherever the caller asks."""
    import json
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return destination


# ---------------------------------------------------------------------------
# Validation
#
# The packaged schema is authoritative; this checks the shape at the point of use so a
# malformed map fails loudly instead of reaching the web viewer.
# ---------------------------------------------------------------------------

_REQUIRED_MODULE_KEYS = {"path", "language", "tier", "last_commit"}
_REQUIRED_EDGE_KEYS = {"from", "to", "kind", "line"}
_REQUIRED_UNKNOWN_KEYS = {"path", "line", "expression", "reason"}


def validate_map(payload: dict) -> None:
    """Raise ValueError if *payload* is not a well-formed repository map.

    Checks types, not just key presence: a `null` where a list belongs would otherwise reach
    the web viewer and break it there, far from the code that produced it.
    """
    if not isinstance(payload, dict):
        raise ValueError("repository map must be an object")
    for key in ("schema_version", "repo", "sha", "generated_at", "modules", "edges", "unknowns", "limits"):
        if key not in payload:
            raise ValueError(f"repository map is missing '{key}'")

    if not isinstance(payload["schema_version"], str):
        raise ValueError("repository map 'schema_version' must be a string")
    for key in ("repo", "sha", "generated_at"):
        if not isinstance(payload[key], str):
            raise ValueError(f"repository map '{key}' must be a string")
    for key in ("modules", "edges", "unknowns"):
        if not isinstance(payload[key], list):
            raise ValueError(f"repository map '{key}' must be an array")
    if not isinstance(payload["limits"], list) or not all(isinstance(l, str) for l in payload["limits"]):
        raise ValueError("repository map 'limits' must be an array of strings")

    for module in payload["modules"]:
        if not isinstance(module, dict) or not _REQUIRED_MODULE_KEYS <= set(module):
            raise ValueError(f"module entry is missing required keys: {module!r}")
        if module["tier"] not in {"full", "static", "static_same_file", "experimental"}:
            raise ValueError(f"unknown tier '{module['tier']}' for {module['path']}")
        if not isinstance(module["path"], str):
            raise ValueError(f"module 'path' must be a string: {module!r}")
    for edge in payload["edges"]:
        if not isinstance(edge, dict) or not _REQUIRED_EDGE_KEYS <= set(edge):
            raise ValueError(f"edge entry is missing required keys: {edge!r}")
        if edge["kind"] != "import":
            raise ValueError(f"unsupported edge kind '{edge['kind']}'")
        if not isinstance(edge["line"], int) or edge["line"] < 1:
            raise ValueError(f"edge 'line' must be a positive integer: {edge!r}")
    for unknown in payload["unknowns"]:
        if not isinstance(unknown, dict) or not _REQUIRED_UNKNOWN_KEYS <= set(unknown):
            raise ValueError(f"unknown entry is missing required keys: {unknown!r}")


def save_for_run(repo_root: Path, evidence: dict, run_dir: Path) -> None:
    """Build the map of the reviewed head commit and store it as ``run_dir/repo_map.json``.

    Shared by `bobreviewer run` and reviews started from the web UI. Raises on failure; callers
    note it and keep the review, which is valid evidence without a map.
    """
    import subprocess
    from tempfile import TemporaryDirectory

    with TemporaryDirectory(prefix="bobreviewer-map-") as tmp:
        checkout = Path(tmp) / "tree"
        added = subprocess.run(
            ["git", "worktree", "add", "--detach", "-q", str(checkout), evidence["head_commit"]],
            cwd=repo_root, capture_output=True, text=True,
        )
        if added.returncode != 0:
            raise RuntimeError(added.stderr.strip() or "git worktree add failed")
        try:
            payload = build(checkout, repo_root, evidence.get("repository", "local"), evidence["head_commit"])
            validate_map(payload)
            write_map(payload, run_dir / "repo_map.json")
        finally:
            subprocess.run(["git", "worktree", "remove", "--force", str(checkout)],
                           cwd=repo_root, capture_output=True, text=True)
