"""
scripts/generate_report.py — Lane 4 (D)

Called by GitHub Actions after bobreviewer run to produce:
  - output/report.md   (Markdown for PR comment)
  - output/report.html (Static HTML viewer)

Usage:
    python scripts/generate_report.py \
        --evidence output/evidence.json \
        --out-md output/report.md \
        --out-html output/report.html \
        --ci-run-url https://github.com/...

Depends on:
    app/report.py       render_markdown(evidence) -> str   [Lane 3]
    app/html_report.py  generate_html(evidence)   -> str   [Lane 3]

If Lane 3's modules are not yet available, this script falls back to a
minimal stub renderer so the CI workflow remains functional.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

# Project root on path
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))


def _stub_render_markdown(evidence: dict) -> str:
    """Minimal Markdown renderer used as fallback when app/report.py is unavailable."""
    fixture_warning = "⚠️ **FIXTURE — not real evidence**\n\n" if evidence.get("fixture") else ""
    base_ref = evidence.get("base_ref", "?")
    head_ref = evidence.get("head_ref", "?")
    run_id = evidence.get("run_id", "?")
    generated_at = evidence.get("generated_at", "?")

    changed = evidence.get("changed_functions", [])
    changed_lines = []
    for fn in changed:
        symbol = fn.get("symbol", "?")
        file_path = fn.get("file_path", "?")
        changed_lines.append(f"- `{symbol}` in `{file_path}`")
        for caller in fn.get("callers", []):
            in_diff = caller.get("in_diff", True)
            label = " **[outside diff]**" if not in_diff else ""
            changed_lines.append(
                f"  - caller: `{caller.get('symbol', '?')}` "
                f"at `{caller.get('file_path', '?')}:{caller.get('line', '?')}`{label}"
            )

    probe_lines = []
    for probe in evidence.get("probe_results", []):
        for case in probe.get("cases", []):
            status = case.get("status", "?").upper()
            probe_lines.append(
                f"| `{case.get('id', '?')}` | `{case.get('base_output')}` "
                f"| `{case.get('head_output')}` | {status} |"
            )

    probe_table = ""
    if probe_lines:
        probe_table = (
            "\n## Probe Results\n\n"
            "| Case | Base | Head | Status |\n"
            "|---|---|---|---|\n"
            + "\n".join(probe_lines)
        )

    limits = evidence.get("analysis_limits", {})
    notes = limits.get("notes", [])
    limits_text = "\n".join(f"- {n}" for n in notes) if notes else "- No additional notes."

    return f"""{fixture_warning}## Behavior Review

**Run:** `{run_id}`  
**Base:** `{base_ref}` → **Head:** `{head_ref}`  
**Generated:** {generated_at}

## Changed Functions

{chr(10).join(changed_lines) if changed_lines else "_No changed functions detected._"}
{probe_table}

## Analysis Limits

{limits_text}

> ⚠️ These cases do not prove general equivalence. Matching tested inputs do not certify correctness.
"""


def _stub_generate_html(evidence: dict) -> str:
    """Minimal HTML viewer used as fallback when app/html_report.py is unavailable."""
    import html as html_module
    md = _stub_render_markdown(evidence)
    safe = html_module.escape(md)
    base_ref = html_module.escape(evidence.get("base_ref", "?"))
    head_ref = html_module.escape(evidence.get("head_ref", "?"))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Behavior Review — {base_ref} → {head_ref}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
    pre {{ background: #f4f4f4; padding: 1rem; overflow-x: auto; }}
    .fixture-warning {{ background: #fff3cd; border: 1px solid #ffc107; padding: .75rem 1rem; margin-bottom: 1rem; }}
  </style>
</head>
<body>
  {"<div class='fixture-warning'>⚠️ FIXTURE — not real evidence. Replace with output from bobreviewer run.</div>" if evidence.get("fixture") else ""}
  <h1>Behavior Review — {base_ref} → {head_ref}</h1>
  <pre>{safe}</pre>
  <p style="font-size:0.75rem;color:#666;margin-top:2rem;border-top:1px solid #eee;padding-top:1rem">
    Generated by bobthereviewer (stub renderer — Lane 3 report module not yet available)
  </p>
</body>
</html>"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Markdown and HTML reports from evidence.json")
    parser.add_argument("--evidence", required=True, help="Path to evidence.json")
    parser.add_argument("--out-md", required=True, help="Output path for Markdown report")
    parser.add_argument("--out-html", required=True, help="Output path for HTML report")
    parser.add_argument("--ci-run-url", default=None, help="CI run URL to embed in report")
    args = parser.parse_args()

    evidence_path = pathlib.Path(args.evidence)
    if not evidence_path.exists():
        print(f"ERROR: evidence file not found: {evidence_path}", file=sys.stderr)
        sys.exit(1)

    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))

    # Patch ci_run_url if provided via CLI
    if args.ci_run_url:
        evidence["ci_run_url"] = args.ci_run_url

    # Try to use Lane 3's real renderers; fall back to stubs if not yet available
    try:
        from app.report import render_markdown
        md = render_markdown(evidence)
    except ImportError:
        print("WARNING: app/report.py not available — using stub Markdown renderer", file=sys.stderr)
        md = _stub_render_markdown(evidence)

    try:
        from app.html_report import generate_html
        html_content = generate_html(evidence)
    except ImportError:
        print("WARNING: app/html_report.py not available — using stub HTML renderer", file=sys.stderr)
        html_content = _stub_generate_html(evidence)

    out_md = pathlib.Path(args.out_md)
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(md, encoding="utf-8")

    out_html = pathlib.Path(args.out_html)
    out_html.parent.mkdir(parents=True, exist_ok=True)
    out_html.write_text(html_content, encoding="utf-8")

    print(f"Report written: {out_md}")
    print(f"HTML viewer written: {out_html}")


if __name__ == "__main__":
    main()
